# Form implementation generated from reading ui file 'TimerButton.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimerButton(object):
    def setupUi(self, TimerButton):
        if not TimerButton.objectName():
            TimerButton.setObjectName(u"TimerButton")
        TimerButton.setObjectName("Ui_TimerButton")
        TimerButton.resize(202, 142)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(TimerButton)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(parent=TimerButton)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(parent=TimerButton)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)

        self.retranslateUi(TimerButton)
        QtCore.QMetaObject.connectSlotsByName(TimerButton)

    def retranslateUi(self, TimerButton):
        _translate = QtCore.QCoreApplication.translate
        TimerButton.setWindowTitle(_translate("TimerButton", "TimerButton"))
        self.pushButton_2.setText(_translate("TimerButton", "Start"))
        self.pushButton.setText(_translate("TimerButton", "Stop"))

